# Generated by Django 4.2.6 on 2023-10-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.TextField()),
                ('premio', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEquipo', models.CharField(max_length=40, unique=True)),
                ('ciudad', models.CharField(max_length=40)),
                ('nombrePropietario', models.CharField(max_length=40)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquiposBaloncesto.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('posicion', models.CharField(max_length=15)),
                ('puntosPorPartido', models.FloatField()),
                ('asistenciasPorPartido', models.FloatField()),
                ('rebotesPorPartido', models.FloatField()),
                ('taponesPorPartido', models.FloatField()),
                ('robosPorPartido', models.FloatField()),
                ('partidosJugados', models.IntegerField()),
                ('añoDraft', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EquiposBaloncesto.equipo')),
            ],
        ),
    ]
