# Generated by Django 4.2.6 on 2023-10-30 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposBaloncesto', '0002_jugador_dorsal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='EquiposBaloncesto.categoria'),
        ),
    ]
