# Generated by Django 4.2.6 on 2023-10-31 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposBaloncesto', '0003_alter_equipo_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='EquiposBaloncesto.equipo'),
        ),
    ]
