# Generated by Django 4.2.6 on 2023-11-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposBaloncesto', '0009_notica_delete_noticia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notica',
            new_name='noticia',
        ),
    ]
