# Generated by Django 4.2.6 on 2023-10-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EquiposBaloncesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='dorsal',
            field=models.IntegerField(default=29),
            preserve_default=False,
        ),
    ]
